### ISSUE TITLE
error：Resource exhausted

### ISSUE THREAD

**Issue by corin-lyz** [HaoZhang1018/PMGI_AAAI2020#2]
Resource exhausted: OOM when allocating tensor with shape[1820,16,120,120] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

How to solve this issues? Thanks

**Comment by HaoZhang1018** [comment]
This error is due to the large size of the source image, and the memory required for calculation exceeds the maximum memory of the GPU used. The first option is to consider using a GPU with more memory.  The second option is to crop the source image with 
large size into multiple small-size image patches (preferably overlapping), and then perform the fusion operation on these image patches. The final result is obtained by splicing these small-size results together.

**Comment by HaoZhang1018** [comment]
> Resource exhausted: OOM when allocating tensor with shape[1820,16,120,120] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> 
> How to solve this issues? Thanks

**Comment by HaoZhang1018** [comment]
> Resource exhausted: OOM when allocating tensor with shape[1820,16,120,120] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> 
> How to solve this issues? Thanks

This error is due to the large size of the source image, and the memory required for calculation exceeds the maximum memory of the GPU used. The first option is to consider using a GPU with larger memory. The second option is to crop the source image with large size into multiple small-size image patches(preferably overlapping), and then perform the fusion operation on these image patches. The final result is obtained by splicing these small-size results together.

**Comment by corin-lyz** [comment]
Thank you for your guidelines and advice! However, the fusion effect becomes totally unacceptable，when I crop the source image with large size into multiple small-size image patches. The reviewer of my paper is looking forward to learning from your paper. I have graduated and started to work, so there is no good experimental environment, if you are convenient, I hope to be able to contact you! My email: 201721010718@alu.uestc.edu.cn, and my QQ: 416390436. I apologize for my unreasonable demands.

**Comment by HaoZhang1018** [comment]
> Thank you for your guidelines and advice! However, the fusion effect becomes totally unacceptable，when I crop the source image with large size into multiple small-size image patches. The reviewer of my paper is looking forward to learning from your paper. I have graduated and started to work, so there is no good experimental environment, if you are convenient, I hope to be able to contact you! My email: [201721010718@alu.uestc.edu.cn](mailto:201721010718@alu.uestc.edu.cn), and my QQ: 416390436. I apologize for my unreasonable demands.

Another simple solution is to use the CPU to test, which can avoid the OOM problem of the GPU. You just need to add in front of the test_one_image.py:

import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"  
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
